### PR TITLE
Expand environment variables when checking file strings

### PR DESCRIPTION
**Pull request by PeterCardenas**
I've been getting false positive diagnostics when sourcing from a file path using the $HOME variable. Thus, I've made all file path parsing parse the environment variables as well.

### CODE REVIEW

**Comment by PeterCardenas** [comment]
btw the diagnostics are very cool, didn't think I needed them but I do!

**Comment by ndonfris** [comment]
Yooo nice work! 

Looks like I completely missed that case while writing the [SyncFileHelper](https://github.com/PeterCardenas/fish-lsp/blob/24a1e4b39d0ba9082979642f5bdd70ba406ed3e8/src/utils/fileOperations.ts#L10). Just going to [add a test](https://github.com/ndonfris/fish-lsp/blob/master/test-data/fileOperations.test.ts) onto this PR, to reflect the new variable expansion support, and then merge it in to master.  

I'm glad you are enjoying the diagnostics! The upcoming releases will certainly focus on extending them, and introducing in some of them with corresponding support for code-actions/quick-fixes. If you want to check out how I built the current Diagnostics, they're tested [here](https://github.com/ndonfris/fish-lsp/blob/master/test-data/diagnostics.test.ts) and provided to the server [here](https://github.com/ndonfris/fish-lsp/blob/master/src/diagnostics/node-types.ts). 

BTW, I was meaning to ask you if any of the changes I made towards the git hooks ended up improving your development environment?

**Comment by PeterCardenas** [comment]
So my biggest gripe was that there was a bunch of unused imports that my autofixer kept removing, and I have a draft PR that fixes those up and fixes the eslintrc, i'll put em up tonight when i find the time

**Comment by ndonfris** [comment]
this [PR](#40) was included in #41

___

On the topic of this PR, I opened a discussion for any insight into the only edge-case I could think of, [fish autoloaded environment variables](https://github.com/ndonfris/fish-lsp/discussions/42). This is a fish related design problem unrelated to `process.env` and therefore I think debating about a potential solution should be entirely separate from the great QOL feature's you've added here. 

_I also suspect that some sort of fallback support will be required to handle this edge-case, as your solution does a great job avoiding runtime efficiency issues._  

___

> So my biggest gripe was that there was a bunch of unused imports that my autofixer kept removing, and I have a draft PR that fixes those up and fixes the eslintrc, i'll put em up tonight when i find the time

I would be super thankful to see that PR come through, hahaha. I've been pumping out structural improvements + new features + test suites & my best attempts at stable releases, which unfortunately has resulted in me avoiding unused files like the plague. Since the prior release, though, I've been refactoring the 'onComplete' handler and the 'src/analyzer.ts' related code (the two locations I thought could use the most improvement). Finishing this refactor should produce noticeable improvements in regard to the codebases'  readability.

**Pull request closed without merging**
